
trigger:
- main

resources:
  containers:
    - container: mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
        - 1433
      env:
        ACCEPT_EULA: Y
        SA_PASSWORD: $(MSSQL_SA_PASSWORD)

variables:
  MSSQL_SA_PASSWORD: "yourStrong(!)Password"

pool:
  vmImage: ubuntu-latest

services:
  sqlserver: mssql

steps:
- task: DockerInstaller@0
  displayName: "Docker: Install tool"
  inputs:
    dockerVersion: "20.10.20"

- script: |
    echo "docker run --rm --network $(Agent.ContainerNetwork) flcdrg/wait-for-mssql --server sqlserver --username sa --password $(MSSQL_SA_PASSWORD)"

    docker run --rm --network $(Agent.ContainerNetwork) flcdrg/wait-for-mssql --server sqlserver --username sa --password $(MSSQL_SA_PASSWORD)
  displayName: Run container