services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - ./.data:/var/opt/mssql/data
    # logging:
    #   driver: none

  wait:
    image: wait-for-mssql:latest
    command: --max 10 --verbose true

    depends_on:
      - mssql
    build:
      context: .
      dockerfile: Dockerfile
